# -*- coding: utf-8 -*-
"""AlphaPulse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13590frZVU-f5Ffn_EC-NaHg8THFl58Fj
"""

import yfinance as yf
import pandas as pd
import numpy as np


# 1) Stocks + Index (Fixed)
stocks = [
    "TCS.NS", "INFY.NS", "HDFCBANK.NS", "ICICIBANK.NS",
    "RELIANCE.NS", "HINDUNILVR.NS", "ITC.NS", "SUNPHARMA.NS",
    "AXISBANK.NS", "LT.NS"
]

index = "^NSEI"
all_tickers = stocks + [index]


# 2) Download Data
start_date = "2020-01-01"
end_date = "2025-12-31"

data = yf.download(all_tickers, start=start_date, end=end_date, auto_adjust=False, progress=False)

adj_close = data["Adj Close"]
volume = data["Volume"]

# 3) Cleaning
adj_close_clean = adj_close.dropna()
volume_clean = volume.loc[adj_close_clean.index]


# 4) Log Returns
log_returns = np.log(adj_close_clean / adj_close_clean.shift(1)).dropna()
# Align after returns
adj_close_clean = adj_close_clean.loc[log_returns.index]
volume_clean = volume_clean.loc[log_returns.index]


# 5) Correlation Matrix
corr_matrix = log_returns.corr()


# 6) Rolling Volatility (30D)
rolling_volatility_30 = log_returns.rolling(30).std()


# 7) Portfolio Daily Returns (Equal Weight)
num_assets = len(all_tickers)
weights = np.array([1/num_assets] * num_assets)

portfolio_returns = log_returns.dot(weights)


# 8) Monte Carlo Simulation (10,000)
initial_investment = 100000
days = 252
simulations = 10000

mu = portfolio_returns.mean()
sigma = portfolio_returns.std()

end_values = []

for _ in range(simulations):
    random_daily_returns = np.random.normal(mu, sigma, days)
    final_value = initial_investment * np.exp(np.sum(random_daily_returns))
    end_values.append(final_value)

end_values = np.array(end_values)
mc_df = pd.DataFrame({"Simulated_End_Value": end_values})


# 9) VaR Report
var_95_value = np.percentile(end_values, 5)
var_99_value = np.percentile(end_values, 1)

loss_95 = initial_investment - var_95_value
loss_99 = initial_investment - var_99_value

var_report = pd.DataFrame({
    "Metric": ["Initial Investment", "VaR 95% Value", "Loss at 95%", "VaR 99% Value", "Loss at 99%"],
    "Amount": [initial_investment, var_95_value, loss_95, var_99_value, loss_99]
})

# 10) Save all outputs in ONE Excel file (Multiple Sheets)
output_file = "AlphaPulse_All_Outputs.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
    adj_close_clean.to_excel(writer, sheet_name="Clean_Adj_Close")
    volume_clean.to_excel(writer, sheet_name="Clean_Volume")
    log_returns.to_excel(writer, sheet_name="Log_Returns")
    corr_matrix.to_excel(writer, sheet_name="Correlation_Matrix")
    rolling_volatility_30.to_excel(writer, sheet_name="Rolling_Volatility_30D")
    portfolio_returns.to_frame(name="Portfolio_Return").to_excel(writer, sheet_name="Portfolio_Returns")
    mc_df.to_excel(writer, sheet_name="MonteCarlo_End_Values", index=False)
    var_report.to_excel(writer, sheet_name="VaR_Report", index=False)

print("✅ Saved successfully:", output_file)

from google.colab import files
files.download("AlphaPulse_All_Outputs.xlsx")